baseURL = 'https://coffeeknife.nekoweb.org/'
languageCode = 'en-us'
title = 'coffeeknife@nekoweb.org'
theme = 'nightfall'

[menu]
  [[menu.header]]
    name = "about"
    weight = 0
    url = "about"
  [[menu.header]]
    name = "tech"
    weight = 1
    url = "tech"

[params]
user = "coffeeknife"
hostname = "nekoweb.org"
sitedescription = "landing page for all my stuff"
footerHtml = '<img src="/images/right2repair.gif" alt="i support right to repair"> <img src="/images/firefoxnow.gif" alt="firefox now"> <a href="https://nekoweb.org/"><img src="https://nekoweb.org/assets/buttons/button11.gif"></a><!-- button by milkyway.moe --> <img src="/images/google_stand.gif" alt="take a stand against google"> <img src="/images/button.png" alt="stop using cloud services">'
  [params.author]
    name = "coffeeknife"  # Website and RSS feed author


readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/coffeeknife"
target = "_blank"
icon = "fa-brands fa-github"
aria = "GitHub Profile"

[[params.social]]
key = 1
name = "bluesky"
url = "https://coffeeknife.bsky.social/"
icon = "fa-brands fa-bluesky"
target = "_blank"
aria = "Bluesky Profile"
rel = "me"
